# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TECMAH BLOG V2
email: "&#105;&#110;&#102;&#111;&#46;&#116;&#101;&#99;&#109;&#97;&#104;&#64;&#103;&#109;&#97;&#105;&#108;&#46;&#99;&#111;&#109;" #HTML Entity
author: TECMAH
copyright: Copyright © 2023
description: >- # this means to ignore newlines until "baseurl:"
  This blog serves as a place to document the thoughts and experiences I gain while embarking on daily new challenges. It's not written specifically for anyone else.
  In facing new challenges, there are often times when I make mistakes, and my viewpoint may differ from those of my readers. However, all of these are part of my valuable experiences.
  What I value here is sharing these challenges and thoughts with you all.
  So, if you share something with me, it will be of great help to my new challenges.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tecmah.com" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/images/favicon/favicon.png" # the favicon for your site
twitter_username: onlyos
github_username:  maurayonori

google_site_verification: Hwkbghj0ak6cDfhDUUsiG6RLJWnvcuEGc27qHdzhqtY
google_analytics: G-HQVQ2Z5P7J
#google_analytics: G-ZDBEM15KK6
enableDNT: "false"

# If you want to generate website sitemap, you can set true
sitemap: true

# theme_color: "#ffffff"
theme_color: snowwhite

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is"manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
#
night_mode: "manual"

# If you want to change the content width, you can set to another value
content_width: "1200px"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - menu/archives.html
  - menu/categories.html
  - menu/tags.html
  - menu/about.md
  - menu/contact.html
  - menu/terms.md

# google_adsense
google_adsense_client: ca-pub-6202067789945516

# sidever pages 
index_page_path: "index.html"
archive_path: "/menu/archives.html"
categories_path: "/menu/categories.html"
tags_path: "/menu/tags.html"

google_form:
  url: https://docs.google.com/forms/u/0/d/e/1FAIpQLSfZcGWu5ISan2WjmzWme3Om_th0yXnnfa4jcG8SyejGpCYWOQ/formResponse
  name_entry: "entry.1199157498"
  email_entry: "entry.923332370"
  subject_entry: "entry.1032018857"
  message_entry: "entry.392222136"


# Pagenation setting
paginate: 10 

# Translate languges
# translate_langs: []

# Disqus comments
# disqus:
#   shortname: "yostecmahmt"

# Build settings
markdown: kramdown
remote_theme: maurayonori/jekyll-theme-yat@develop

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-remote-theme


jekyll_compose:
  default_front_matter:
    drafts:
      title: The Frameworks of Effective Product Design Sense
      subtitle: Craft products better with better systematic design judgment
      banner:
        image: "/assets/images/newbusinessflowchart/pro.png)"
        opacity: 0.3
      category: Engineering/General/Philosophy/History/Social Sciences/Natural Sciences/Applied Sciences/Arts/Sports/Health and Medicine/Language and Literature/Culture and Education/Geography, History, and Biography/Kindle
      tags: Hardware/Software/Network/Security/Software Engineering/Information Systems/Artificial Intelligence/Theory of Computation/Human-Computer Interaction
    posts:
      title: The Frameworks of Effective Product Design Sense
      subtitle: Craft products better with better systematic design judgment
      banner:
        image: "/assets/images/newbusinessflowchart/pro.png)"
        opacity: 0.3
      category: Engineering/General/Philosophy/History/Social Sciences/Natural Sciences/Applied Sciences/Arts/Sports/Health and Medicine/Language and Literature/Culture and Education/Geography, History, and Biography/Kindle
      tags: Hardware/Software/Network/Security/Software Engineering/Information Systems/Artificial Intelligence/Theory of Computation/Human-Computer Interaction

#      published: false
#      sitemap: false
#    auto_open: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.

markdown: kramdown
kmarkdown:
  input: GFM

#
exclude:
  - app/*
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
