# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: TECMAH BLOG V2
email: info.tecmah@google.com
author: TECMAH
copyright: Copyright © 2023
description: >- # this means to ignore newlines until "baseurl:"
  This blog serves as a place to document the thoughts and experiences I gain while embarking on daily new challenges. It's not written specifically for anyone else.
  In facing new challenges, there are often times when I make mistakes, and my viewpoint may differ from those of my readers. However, all of these are part of my valuable experiences.
  What I value here is sharing these challenges and thoughts with you all.
  So, if you share something with me, it will be of great help to my new challenges.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.tecmah.com" # the base hostname & protocol for your site, e.g. http://example.com
favicon: "/assets/images/favicon/favicon.png" # the favicon for your site
twitter_username: onlyos
github_username:  maurayonori

google_site_verification: Hwkbghj0ak6cDfhDUUsiG6RLJWnvcuEGc27qHdzhqtY
google_analytics: G-HQVQ2Z5P7J
enableDNT: "false"

# If you want to generate website sitemap, you can set true
sitemap: true

# theme_color: "#ffffff"
theme_color: snowwhite

# If you want to change the content width, you can set to another value
content_width: "1200px"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
  - index.html
  - menu/archives.html
  - menu/categories.html
  - menu/tags.html
  - menu/about.md
  - menu/contact.html

google_form:
  url: GOOGLE_FORM_URL
  name_entry: "entry.1199157498"
  email_entry: "entry.923332370"
  subject_entry: "entry.1032018857"
  message_entry: "entry.392222136"


# Pagenation setting
paginate: 10 

# Disqus comments
# disqus:
#   shortname: "yostecmahmt"

# Build settings
markdown: kramdown
remote_theme: maurayonori/jekyll-theme-yat@develop

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-spaceship
  - jekyll-remote-theme


jekyll_compose:
  default_front_matter:
    drafts:
#      description:
#      image:
      category: development news
      tags:
    posts:
      description:
      image:
      category: blog
      tags: development news
#      published: false
#      sitemap: false
#    auto_open: true
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
